<template>
    <div>
      <v-row>
        <v-col>
            test1
        </v-col>
        <v-col>
            test2
        </v-col>
      </v-row>
      <v-row>
        <v-col>
            test1
        </v-col>
        <v-col>
            test2
        </v-col>
      </v-row>
      <v-row>
        <v-col>
            test1
        </v-col>
        <v-col>
            test2
        </v-col>
      </v-row>
    </div>
</template>